version: '3'
services:
  neo4j:
    image: neo4j:4.3.2
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data:/data
      - ./plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/password
    command: neo4j
